---
- name: User Playbook
  hosts: all
  become: yes
  become_method: sudo
  user: centos
  tasks:
  - name: User add bob
    user:
     name: bob
     state: absent
  - name: User add lisa
    user:
     name: lisa
     state: absent



      